### ISSUE TITLE
class_email_templates.php was encoded by the ionCube Encoder for PHP 5.6 and cannot run under PHP 7.1 or later

### ISSUE THREAD

**Issue by velirs** [bjohnson045/phpMyDirectory#12]
Fatal error: The file /var/www/vhosts/resellers.directory/httpdocs/includes/class_email_templates.php was encoded by the ionCube Encoder for PHP 5.6 and cannot run under PHP 7.1 or later. Please ask the provider of the script to provide a version encoded with the ionCube Encoder for PHP 7.1. in Unknown on line 0

**Comment by markdaps** [comment]
Looks like this file was missed from the ioncube decoding process.

I've now posted this in the beta testing forum.

**Comment by tonymartini** [comment]
Sorry Ben I do not see it. All of my sites are now all down. How do I fix this and where is the ioncube decoding file that is fixed.
Thanx

**Comment by CloudedDesire** [comment]
If you need any other files, I have 'em all. 
[class_email_templates.zip](https://github.com/bjohnson045/phpMyDirectory/files/6189216/class_email_templates.zip)

**Comment by bjohnson045** [comment]
I have checked the repository here and /includes/class_email_templates.php is not encoded. Please try using the file provided in the repo.

https://github.com/bjohnson045/phpMyDirectory/blob/master/includes/class_email_templates.php
