### ISSUE TITLE
All sites are down with error message 

### ISSUE THREAD

**Issue by tonymartini** [bjohnson045/phpMyDirectory#13]
All ofmy sites  are down. I get the error message below.

==========================

Fatal error: The file /home/camping/public_html/includes/class_factory.php was encoded by the ionCube Encoder for PHP 5.6 and cannot run under PHP 7.1 or later. Please ask the provider of the script to provide a version encoded with the ionCube Encoder for PHP 7.1. in Unknown on line 0
===========================

How do I fix this. Step by step instructions please.

Also, please read my support tickets I posted sometime ago.

Thanx.

**Comment by bjohnson045** [comment]
You will want to use the open source version that no longer uses ion cube. Your servers software was updated and caused the older ioncube version to fail.
