### ISSUE TITLE
License and Services Link Broken

### ISSUE THREAD

**Issue by fiesh27** [bjohnson045/phpMyDirectory#22]
I am trying to go through the download instructions and the 'click here' for license and services links to a critical error. Is it something I am doing?? Do I just not understand what to do??

**Comment by bailaho** [comment]
No, you cannot login into Client Area on phpmydirectory.com at the moment. There is no connection to database.

**Comment by bjohnson045** [comment]
@fiesh27 @bailaho You can download the software here on Github. https://github.com/bjohnson045/phpMyDirectory/tags
