### ISSUE TITLE
license error

### ISSUE THREAD

**Issue by truthonlytruth11** [bjohnson045/phpMyDirectory#26]
how can i get rid of this?
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
License Error
There was a problem validating your software license.
- Verify your license code is in defaults.php
- Try reissueing your license.

If you still receive problems, please contact support.
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by moonslice** [comment]
I have same problem - and I can't get to phpmydirectory.com nor the manual nor the forum.

I've tried emailing Ben at ben@phpmydirectory.com. I'm just hoping he gets my message and fixes it.

Ben said he would never require license validation if he shut down the server, so this is very upsetting. My whole career is on this Directory! It's horrible!!!!!!!!!!!!!!!!!!

**Comment by truthonlytruth11** [comment]
I wonder if we need to upload the new version that posted here to fix the problem????
Does anyone know which file needs to be edited???????

**Comment by bjohnson045** [comment]
@truthonlytruth11 Yes the software is now open source. You may upload the unencrypted files and they do not include any license validation code.

**Comment by truthonlytruth11** [comment]
When I reuploaded CP folder fix the problem.... :)

**Comment by moonslice** [comment]
> When I reuploaded CP folder fix the problem.... :)

@truthonlytruth11 - Are you saying you overwrote your existing directory files with the opensource files? Or did you have a backup of your actual directory files and you just overwrote your site with a backup copy of your own actual site?

Did you have to overwrite all files or just a few specific ones?

Are you on 1.5.3? I'm on 1.5.1 and am awaiting Ben to email me the 1.5.1 opensource files.

Thank You!

**Comment by truthonlytruth11** [comment]
I am on 1.5.3 PHP 7.3
I overwrite CP directory with opensource code from github... that's all
