### ISSUE TITLE
Admin Page not working

### ISSUE THREAD

**Issue by sirslmarx** [bjohnson045/phpMyDirectory#27]
I cannot log into my admin page, What has gone wrong and how do i fix this.

**Comment by moonslice** [comment]
I have same problem - and I can't get to phpmydirectory.com nor the manual nor the forum.

I've tried emailing Ben at ben@phpmydirectory.com. I'm just hoping he gets my message and fixes it.

Ben said he would never require license validation if he shut down the server, so this is very upsetting. My whole career is on this Directory! It's horrible!!!!!!!!!!!!!!!!!!

**Comment by nolliug** [comment]
Guys, this directory script is dead. I had the same problems a year ago. No one will come with a proper answer. I once had a "Ben" to answer me from a Gmail address with crap answers, not even sure it was him. My advice: don't waste your time.

**Comment by bjohnson045** [comment]
@sirslmarx phpMyDirectory is now open source. You can replace any of the encrypted files with the open source versions here on GitHub to remove the license restriction.

**Comment by bjohnson045** [comment]
@moonslice You may view the manual here:
https://phpmydirectory.atlassian.net/wiki/spaces/PMDDOC/overview?homepageId=10748177

Please provide an email address and we can email you version 1.5.1.

**Comment by sirslmarx** [comment]
Ben, 

Thank you for this answer, however, I am not a coder, I don’t understand how to make the changes for this to work. I read you Manual and I don’t even know where to start to fix this. Is there anyone I can pay to fix my admin Login? 

Sir Samuel Marx

**Comment by tonymartini** [comment]
Hi Samuel, 

if you need help let me know.

Tony

**Comment by bjohnson045** [comment]
@sirslmarx You will want to work with a programmer to get your site updated. One place to check is also Upwork.com for hire programmers.

**Comment by sirslmarx** [comment]
Tony i need help with another issue i am having Fatal error: Call to undefined method Locations::getFullCount() in /home/sirsam/public_html/cp/admin_locations.php on line 26 

Can you help?

**Comment by tonymartini** [comment]
Hi Marx,
The problem is more likely in the data. You will have to check for an extra , (COMMA ) or one missing.
If you want I can take a look inside your CP and your raw data that you uploaded.

Tony

**Comment by sirslmarx** [comment]
Tony, 

Can you email me sam@ratedtrades.us so we can discuss this. It has only stopped working today, I have been adding lots of new locations but have realized i dont need some.

**Comment by sirslmarx** [comment]
Tony, 

Email will not work my Internet Service Provider will not send emails to Hotmail accounts, can i call you? In the meantime My site is not down, it is working fine on the front end. See [www.ratedtrades.us](http://www.ratedtrades.us/) 

The problem I am having is on the admin side of PHP My Directory. See error log. Fatal error: Call to undefined method Locations::getFullCount() in /home/sirsam/public_html/cp/admin_locations.php on line 26

Up till yesterday I was able to delete locations on the admin page but now I can’t. I also see another error when I click on the Location Set Up Wizard and that is 

There was a problem validating your software license.
- Verify your license code is in defaults.php
- Try reissuing your license.

Now seeing as there is no license anymore as its open source now, and this is a new error, I don’t think this is causing the inability to delete locations. 

Can you please tell me how much experience you have in working with PHP my Directory? And if you have any examples of your work?
