### ISSUE TITLE
As this is anounced as OpenSource

### ISSUE THREAD

**Issue by velirs** [bjohnson045/phpMyDirectory#3]
Hi

Just to understand, after announcing that PhpMyDirectory is Opensource, **do I need to purchase the license key to use the Opensource software?**

Regards,
Kumaresan

**Comment by bjohnson045** [comment]
No, a license key is no longer required.

**Comment by velirs** [comment]
While trying to install it ask for license. 
How can I try this software

Regards
Kumaresan

**Comment by velirs** [comment]
Ben Thanks for your reply;

I tried to source from GetitHub; still it is asking for License for Installation

 

Best Regards,

Kumaresan Pandurangan, Sales & Strategic Marketing 

Office : 20401, Mobile : +91 9910517595

**Comment by velirs** [comment]
Best Regards,

Kumaresan Pandurangan, Sales & Strategic Marketing 

Office : 20401, Mobile : +91 9910517595

**Comment by b4allb4u** [comment]
Why it is asking license key at the time of installation.  Is a license key required to install this software?
