### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by lesabrams** [bjohnson045/phpMyDirectory#43]
I am using phpmydirectory and am having problems logging in. We had a power outage yesterday and this morning i cannot access my Control Panel. I am just getting teh error message that i have used so many login attempts and when i get to 5 attempts i will need to wait 15 minutes. I have waited in excess of teh time requested but still cannot access my CP.

How can i resolve this urgent problem?

**Comment by bailaho** [comment]
So if this problem appears you wait 15 minutes, try "forget password"-option, set new password and you should be able to access the cp again.

**Comment by lesabrams** [comment]
Many thanks i had already tried that and yes it worked...

**Comment by bailaho** [comment]
Nothing to thanks. Wish you all the best!
